channel = 12;

data = readtable(sprintf('results/sample_entropy_ch%d.csv', channel));
data.Group = categorical(data.Group);

err_y_mean = [...
  mean(data{ismember(data.Group, {'>=26-PRE'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'<26-PRE'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'>=26-TERM'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'<26-TERM'}),'Sample_Entropy'})...
];
err_y_std = [...
  std(data{ismember(data.Group, {'>=26-PRE'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'<26-PRE'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'>=26-TERM'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'<26-TERM'}),'Sample_Entropy'})...
];
err_x_mean = [...
  mean(data{ismember(data.Group, {'>=26-PRE'}),'Rec_Time'})...
  mean(data{ismember(data.Group, {'<26-PRE'}),'Rec_Time'})...
  mean(data{ismember(data.Group, {'>=26-TERM'}),'Rec_Time'})...
  mean(data{ismember(data.Group, {'<26-TERM'}),'Rec_Time'})...
];
err_x_std = [...
  std(data{ismember(data.Group, {'>=26-PRE'}),'Rec_Time'})...
  std(data{ismember(data.Group, {'<26-PRE'}),'Rec_Time'})...
  std(data{ismember(data.Group, {'>=26-TERM'}),'Rec_Time'})...
  std(data{ismember(data.Group, {'<26-TERM'}),'Rec_Time'})...
];

preIndex = ismember(data.Group, {'>=26-PRE', '<26-PRE'});
termIndex = ismember(data.Group, {'>=26-TERM', '<26-TERM'});

clf;
hold on;

sP = scatter(data{preIndex,'Rec_Time'}, data{preIndex,'Sample_Entropy'}, 15, 'k', 'filled');
errorbar(err_x_mean(1:2), err_y_mean(1:2), err_y_std(1:2), err_y_std(1:2), err_x_std(1:2), err_x_std(1:2), 'sr');

sT = scatter(data{termIndex,'Rec_Time'}, data{termIndex,'Sample_Entropy'}, 15, 'k');
errorbar(err_x_mean(3:4), err_y_mean(3:4), err_y_std(3:4), err_y_std(3:4), err_x_std(3:4), err_x_std(3:4), 'sg');

legend({'PRE', 'PRE \mu, \sigma', 'TERM', 'TERM \mu, \sigma'}, 'Location','southeast');

text(25.8,1.35,'Early', 'HorizontalAlignment','right');
text(26.2,1.35,'Late');
xline(26, '--k', 'HandleVisibility','off');

title(sprintf('Sample entropy (m=3, r=0.15, channel=%d)', channel));
xlabel('Recording time [weeks]');
ylabel('Sampling entropy [units]');

sP.DataTipTemplate.DataTipRows(1).Label = 'Recording time [weeks]';
sP.DataTipTemplate.DataTipRows(2).Label = 'Sampling entropy [units]';
sP.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow('Record',data.Record(preIndex));

sT.DataTipTemplate.DataTipRows(1).Label = 'Recording time [weeks]';
sT.DataTipTemplate.DataTipRows(2).Label = 'Sampling entropy [units]';
sT.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow('Record',data.Record(termIndex));

set(gcf, 'PaperPosition', [0 0 5 5]);
set(gcf, 'PaperSize', [5 5]);
saveas(gcf, sprintf('results/sample_entropy_rec_time_ch%d.pdf', channel));