channel = 12;

metadata = readtable('results/tpehgdb_metadata.csv');
data = readtable(sprintf('results/sample_entropy_ch%d.csv', channel));
data.Group = categorical(data.Group);
data.Gestation = metadata.Gestation;

err_y_mean = [...
  mean(data{ismember(data.Group, {'<26-PRE'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'<26-TERM'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'>=26-PRE'}),'Sample_Entropy'})...
  mean(data{ismember(data.Group, {'>=26-TERM'}),'Sample_Entropy'})...
];
err_y_std = [...
  std(data{ismember(data.Group, {'<26-PRE'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'<26-TERM'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'>=26-PRE'}),'Sample_Entropy'})...
  std(data{ismember(data.Group, {'>=26-TERM'}),'Sample_Entropy'})...
];
err_x_mean = [...
  mean(data{ismember(data.Group, {'<26-PRE'}),'Gestation'})...
  mean(data{ismember(data.Group, {'<26-TERM'}),'Gestation'})...
  mean(data{ismember(data.Group, {'>=26-PRE'}),'Gestation'})...
  mean(data{ismember(data.Group, {'>=26-TERM'}),'Gestation'})...
];
err_x_std = [...
  std(data{ismember(data.Group, {'<26-PRE'}),'Gestation'})...
  std(data{ismember(data.Group, {'<26-TERM'}),'Gestation'})...
  std(data{ismember(data.Group, {'>=26-PRE'}),'Gestation'})...
  std(data{ismember(data.Group, {'>=26-TERM'}),'Gestation'})...
];

earlyIndex = ismember(data.Group, {'<26-PRE', '<26-TERM'});
lateIndex = ismember(data.Group, {'>=26-TERM', '>=26-PRE'});

clf;
hold on;

sP = scatter(data{earlyIndex,'Gestation'}, data{earlyIndex,'Sample_Entropy'}, 15, 'k', 'filled');
errorbar(err_x_mean(1:2), err_y_mean(1:2), err_y_std(1:2), err_y_std(1:2), err_x_std(1:2), err_x_std(1:2), 'sr');

sT = scatter(data{lateIndex,'Gestation'}, data{lateIndex,'Sample_Entropy'}, 15, 'k');
errorbar(err_x_mean(3:4), err_y_mean(3:4), err_y_std(3:4), err_y_std(3:4), err_x_std(3:4), err_x_std(3:4), 'sg');

legend({'Early', 'Early \mu, \sigma', 'Late', 'Late \mu, \sigma'}, 'Location','southeast');

text(36.8,1.35,'PRE', 'HorizontalAlignment','right');
text(37.2,1.35,'TERM');
xline(37, '--k', 'HandleVisibility','off');

title(sprintf('Sample entropy (m=3, r=0.15, channel=%d)', channel));
xlabel('Gestation time [weeks]');
ylabel('Sampling entropy [units]');

sP.DataTipTemplate.DataTipRows(1).Label = 'Gestation time [weeks]';
sP.DataTipTemplate.DataTipRows(2).Label = 'Sampling entropy [units]';
sP.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow('Record',data.Record(earlyIndex));

sT.DataTipTemplate.DataTipRows(1).Label = 'Gestation time [weeks]';
sT.DataTipTemplate.DataTipRows(2).Label = 'Sampling entropy [units]';
sT.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow('Record',data.Record(lateIndex));

set(gcf, 'PaperPosition', [0 0 5 5]);
set(gcf, 'PaperSize', [5 5]);
saveas(gcf, sprintf('results/sample_entropy_gestation_ch%d.pdf', channel));